services:

  spark:
    build: ./docker
    container_name: spark-container
    volumes:
      - ./:/app
    working_dir: /app
    command: tail -f /dev/null
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: healthcare
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  api:
    build: ./docker
    container_name: flask-api
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: python api/app.py
    ports:
      - "5000:5000"
    depends_on:
      - spark
  dashboard:
    build: ./docker
    container_name: streamlit-ui
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: streamlit run dashboard/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  pgdata: